spring:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: true
      javax:
        persistence:
          validation:
            mode: none
  security:
    user:
      name: admin
      password: 123456
      roles: ADMIN